apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapKeyRef:
        name: nginx-config 
    # env: 
    #   - name: course
    #     valueFrom:
    #       configMapKeyRef:
    #         name: nginx-config # name of the config map you are referring to
    #         key: course # env.name and config map key name can be different
    #   - name: duration
    #     valueFrom:
    #       configMapKeyRef:
    #         name: nginx-config
    #         key: duration         